spring.application.name=platform
spring.jpa.properties.hibernate.default_schema=animal_platform

# PostgreSQL DB config
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# definindo a senha do secret (security)
api.security.token.secret=${JWT_SECRET:12345678}