spring.application.name=platform
spring.jpa.properties.hibernate.default_schema=public

# PostgreSQL DB config
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Create schema if it doesn't exist
spring.jpa.hibernate.default_schema=animal_platform

# Or let Hibernate create it
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# definindo a senha do secret (security)
api.security.token.secret=${JWT_SECRET:12345678}

app.security.enable=false